-- AssetIQ Backend — MySQL schema (CREATE TABLE statements)
--
-- Snapshot generated from the local dev database, which Liquibase built
-- from the changesets in src/main/resources/db/changelog/changes/.
-- Liquibase owns the schema at runtime (ddl-auto: validate) — this file is
-- a reference/export for manual provisioning, not something the app reads.
-- The `databasechangelog` / `databasechangeloglock` bookkeeping tables that
-- Liquibase creates automatically are omitted.

CREATE TABLE `aiq_ai_vision_result_log` (
  `id` bigint NOT NULL,
  `tenant_id` varchar(50) NOT NULL,
  `visit_capture_id` bigint NOT NULL,
  `asset_id` bigint NOT NULL,
  `photo_url` varchar(500) NOT NULL,
  `model_version` varchar(20) NOT NULL,
  `detected_purity_pct` decimal(5,2) DEFAULT NULL,
  `detected_condition` varchar(20) DEFAULT NULL,
  `detected_brand` varchar(50) DEFAULT NULL,
  `confidence_score` decimal(5,2) DEFAULT NULL,
  `raw_result` varchar(2000) DEFAULT NULL,
  `processing_status` varchar(20) NOT NULL DEFAULT 'PENDING',
  `processed_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_ai_vision_tenant_asset` (`tenant_id`,`asset_id`),
  KEY `idx_ai_vision_tenant_visit_capture` (`tenant_id`,`visit_capture_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `aiq_asset` (
  `id` bigint NOT NULL,
  `tenant_id` varchar(50) NOT NULL,
  `asset_number` varchar(30) NOT NULL,
  `serial_number` varchar(50) NOT NULL,
  `asset_name` varchar(100) NOT NULL,
  `category_code` varchar(30) NOT NULL,
  `type_code` varchar(30) NOT NULL,
  `model_code` varchar(30) NOT NULL,
  `vendor_code` varchar(30) DEFAULT NULL,
  `brand_code` varchar(30) DEFAULT NULL,
  `division_code` varchar(30) DEFAULT NULL,
  `company_code` varchar(20) DEFAULT NULL,
  `capacity` decimal(10,2) DEFAULT NULL,
  `capacity_unit` varchar(20) DEFAULT NULL,
  `colour` varchar(30) DEFAULT NULL,
  `purchase_date` date NOT NULL,
  `purchase_price` decimal(14,2) NOT NULL,
  `purchase_order_ref` varchar(50) DEFAULT NULL,
  `invoice_ref` varchar(50) DEFAULT NULL,
  `manufacturing_date` date DEFAULT NULL,
  `warranty_start_date` date DEFAULT NULL,
  `warranty_end_date` date DEFAULT NULL,
  `warranty_type` varchar(20) DEFAULT NULL,
  `amc_start_date` date DEFAULT NULL,
  `amc_end_date` date DEFAULT NULL,
  `amc_vendor_code` varchar(30) DEFAULT NULL,
  `depreciation_method` varchar(5) DEFAULT NULL,
  `useful_life_years` smallint DEFAULT NULL,
  `residual_value` decimal(14,2) DEFAULT NULL,
  `asset_status` varchar(30) NOT NULL DEFAULT 'STOCK',
  `working_status` varchar(20) DEFAULT NULL,
  `condition_grade` varchar(20) DEFAULT NULL,
  `location_type` varchar(20) DEFAULT NULL,
  `location_code` varchar(50) DEFAULT NULL,
  `territory_code` varchar(30) DEFAULT NULL,
  `salesman_code` varchar(30) DEFAULT NULL,
  `installation_date` date DEFAULT NULL,
  `last_visit_date` date DEFAULT NULL,
  `last_visit_id` varchar(50) DEFAULT NULL,
  `ahs_score` decimal(5,2) DEFAULT NULL,
  `ahs_presence_score` decimal(5,2) DEFAULT NULL,
  `ahs_purity_score` decimal(5,2) DEFAULT NULL,
  `ahs_condition_score` decimal(5,2) DEFAULT NULL,
  `ahs_uptime_score` decimal(5,2) DEFAULT NULL,
  `ahs_pl_factor` decimal(5,2) DEFAULT NULL,
  `ahs_confidence_level` varchar(10) DEFAULT NULL,
  `ahs_calculated_at` timestamp NULL DEFAULT NULL,
  `ahs_stale_flag` tinyint NOT NULL DEFAULT '0',
  `ahs_stale_since` timestamp NULL DEFAULT NULL,
  `primary_photo_url` varchar(500) DEFAULT NULL,
  `document_refs` varchar(1000) DEFAULT NULL,
  `created_by` varchar(50) NOT NULL,
  `created_at` timestamp NOT NULL,
  `updated_by` varchar(50) NOT NULL,
  `updated_at` timestamp NOT NULL,
  `is_active` tinyint NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_asset_tenant_asset_number` (`tenant_id`,`asset_number`),
  UNIQUE KEY `ux_asset_tenant_category_serial` (`tenant_id`,`category_code`,`serial_number`),
  KEY `idx_asset_tenant_location` (`tenant_id`,`location_type`,`location_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `aiq_asset_association` (
  `id` bigint NOT NULL,
  `tenant_id` varchar(50) NOT NULL,
  `asset_id` bigint NOT NULL,
  `asset_number` varchar(30) NOT NULL,
  `location_type` varchar(20) NOT NULL,
  `location_code` varchar(50) NOT NULL,
  `location_name` varchar(100) DEFAULT NULL,
  `territory_code` varchar(30) DEFAULT NULL,
  `salesman_code` varchar(30) DEFAULT NULL,
  `custodian_name` varchar(100) DEFAULT NULL,
  `custodian_phone` varchar(20) DEFAULT NULL,
  `assignment_date` date NOT NULL,
  `expected_return_date` date DEFAULT NULL,
  `assignment_type` varchar(20) NOT NULL DEFAULT 'PERMANENT',
  `assignment_ref` varchar(50) DEFAULT NULL,
  `has_contract` tinyint NOT NULL DEFAULT '0',
  `contract_ref` varchar(50) DEFAULT NULL,
  `deposit_amount` decimal(14,2) DEFAULT NULL,
  `deposit_status` varchar(20) DEFAULT NULL,
  `exclusivity_flag` tinyint NOT NULL DEFAULT '0',
  `purity_clause_pct` decimal(5,2) DEFAULT NULL,
  `contract_start_date` date DEFAULT NULL,
  `contract_end_date` date DEFAULT NULL,
  `contract_document_url` varchar(500) DEFAULT NULL,
  `is_active` tinyint NOT NULL DEFAULT '1',
  `created_by` varchar(50) NOT NULL,
  `created_at` timestamp NOT NULL,
  `updated_at` timestamp NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_asset_assoc_tenant_asset` (`tenant_id`,`asset_id`),
  KEY `idx_asset_assoc_tenant_location` (`tenant_id`,`location_type`,`location_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `aiq_asset_catalog` (
  `id` bigint NOT NULL,
  `tenant_id` varchar(50) NOT NULL,
  `level` varchar(10) NOT NULL,
  `code` varchar(30) NOT NULL,
  `name` varchar(100) NOT NULL,
  `parent_code` varchar(30) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `manufacturer_name` varchar(100) DEFAULT NULL,
  `manufacturer_country` varchar(50) DEFAULT NULL,
  `manufacturer_contact_email` varchar(100) DEFAULT NULL,
  `manufacturer_contact_phone` varchar(20) DEFAULT NULL,
  `default_warranty_months` smallint DEFAULT NULL,
  `default_useful_life_years` smallint DEFAULT NULL,
  `default_depreciation_method` varchar(5) DEFAULT NULL,
  `default_pm_frequency_days` smallint DEFAULT NULL,
  `default_purity_clause_pct` decimal(5,2) DEFAULT NULL,
  `capacity` decimal(10,2) DEFAULT NULL,
  `capacity_unit` varchar(20) DEFAULT NULL,
  `is_active` tinyint NOT NULL DEFAULT '1',
  `created_at` timestamp NOT NULL,
  `updated_at` timestamp NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_asset_catalog_tenant_level_code` (`tenant_id`,`level`,`code`),
  KEY `idx_asset_catalog_tenant_parent_code` (`tenant_id`,`parent_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `aiq_asset_movement_log` (
  `id` bigint NOT NULL,
  `tenant_id` varchar(50) NOT NULL,
  `asset_id` bigint NOT NULL,
  `asset_number` varchar(30) NOT NULL,
  `movement_type` varchar(30) NOT NULL,
  `from_location_type` varchar(20) DEFAULT NULL,
  `from_location_code` varchar(50) DEFAULT NULL,
  `to_location_type` varchar(20) DEFAULT NULL,
  `to_location_code` varchar(50) DEFAULT NULL,
  `moved_by_user_code` varchar(50) NOT NULL,
  `approved_by_user_code` varchar(50) DEFAULT NULL,
  `approval_ref` varchar(50) DEFAULT NULL,
  `reason` varchar(255) DEFAULT NULL,
  `gps_lat` decimal(10,8) DEFAULT NULL,
  `gps_lng` decimal(11,8) DEFAULT NULL,
  `photo_before_url` varchar(500) DEFAULT NULL,
  `photo_after_url` varchar(500) DEFAULT NULL,
  `signature_url` varchar(500) DEFAULT NULL,
  `notes` varchar(500) DEFAULT NULL,
  `moved_at` timestamp NOT NULL,
  `created_at` timestamp NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_asset_movement_tenant_asset` (`tenant_id`,`asset_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `aiq_asset_request` (
  `id` bigint NOT NULL,
  `tenant_id` varchar(50) NOT NULL,
  `request_number` varchar(50) NOT NULL,
  `outlet_code` varchar(50) NOT NULL,
  `outlet_name` varchar(100) DEFAULT NULL,
  `territory_code` varchar(30) DEFAULT NULL,
  `salesman_code` varchar(50) NOT NULL,
  `category_code` varchar(30) NOT NULL,
  `type_code` varchar(30) NOT NULL,
  `reason` varchar(255) DEFAULT NULL,
  `status` varchar(20) NOT NULL,
  `requested_by_user_code` varchar(50) NOT NULL,
  `requested_at` timestamp NOT NULL,
  `approved_asset_id` bigint DEFAULT NULL,
  `approved_by_user_code` varchar(50) DEFAULT NULL,
  `approved_at` timestamp NULL DEFAULT NULL,
  `rejection_reason` varchar(255) DEFAULT NULL,
  `rejected_by_user_code` varchar(50) DEFAULT NULL,
  `rejected_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL,
  `updated_at` timestamp NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_asset_request_tenant_number` (`tenant_id`,`request_number`),
  KEY `idx_asset_request_tenant_status` (`tenant_id`,`status`),
  KEY `idx_asset_request_tenant_outlet` (`tenant_id`,`outlet_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `aiq_iot_telemetry_log` (
  `id` bigint NOT NULL,
  `tenant_id` varchar(50) NOT NULL,
  `asset_id` bigint NOT NULL,
  `asset_number` varchar(30) NOT NULL,
  `device_id` varchar(50) NOT NULL,
  `metric_type` varchar(30) NOT NULL,
  `metric_value` varchar(50) NOT NULL,
  `metric_unit` varchar(20) DEFAULT NULL,
  `alert_triggered` tinyint NOT NULL DEFAULT '0',
  `alert_type` varchar(50) DEFAULT NULL,
  `captured_at` timestamp NOT NULL,
  `received_at` timestamp NOT NULL,
  `created_at` timestamp NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_iot_telemetry_tenant_asset` (`tenant_id`,`asset_id`),
  KEY `idx_iot_telemetry_tenant_device` (`tenant_id`,`device_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `aiq_role_config` (
  `id` bigint NOT NULL,
  `tenant_id` varchar(50) NOT NULL,
  `role_code` varchar(30) NOT NULL,
  `role_name` varchar(100) NOT NULL,
  `asset_capture_eligible` tinyint NOT NULL DEFAULT '0',
  `description` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL,
  `updated_at` timestamp NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_role_config_tenant_role` (`tenant_id`,`role_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `aiq_scoring_config` (
  `id` bigint NOT NULL,
  `tenant_id` varchar(50) NOT NULL,
  `presence_weight_pct` decimal(5,2) NOT NULL,
  `purity_weight_pct` decimal(5,2) NOT NULL,
  `condition_weight_pct` decimal(5,2) NOT NULL,
  `uptime_weight_pct` decimal(5,2) NOT NULL,
  `created_at` timestamp NOT NULL,
  `updated_at` timestamp NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_scoring_config_tenant` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `aiq_service_event_log` (
  `id` bigint NOT NULL,
  `tenant_id` varchar(50) NOT NULL,
  `event_number` varchar(20) NOT NULL,
  `event_type` varchar(20) NOT NULL,
  `asset_id` bigint NOT NULL,
  `asset_number` varchar(30) NOT NULL,
  `outlet_code` varchar(50) NOT NULL,
  `visit_id` varchar(50) DEFAULT NULL,
  `priority` varchar(20) NOT NULL,
  `status` varchar(30) NOT NULL DEFAULT 'OPEN',
  `description` varchar(500) DEFAULT NULL,
  `raised_by_user_code` varchar(50) NOT NULL,
  `assigned_to_user_code` varchar(50) DEFAULT NULL,
  `resolved_at` timestamp NULL DEFAULT NULL,
  `closed_at` timestamp NULL DEFAULT NULL,
  `resolution_notes` varchar(500) DEFAULT NULL,
  `photo_url_1` varchar(500) DEFAULT NULL,
  `photo_url_2` varchar(500) DEFAULT NULL,
  `photo_after_url` varchar(500) DEFAULT NULL,
  `signature_url` varchar(500) DEFAULT NULL,
  `gps_lat` decimal(10,8) DEFAULT NULL,
  `gps_lng` decimal(11,8) DEFAULT NULL,
  `complaint_type` varchar(50) DEFAULT NULL,
  `is_under_warranty` tinyint NOT NULL DEFAULT '0',
  `is_repeated` tinyint NOT NULL DEFAULT '0',
  `parent_event_number` varchar(20) DEFAULT NULL,
  `customer_rating` smallint DEFAULT NULL,
  `wo_type` varchar(20) DEFAULT NULL,
  `triggered_by` varchar(20) DEFAULT NULL,
  `planned_date` date DEFAULT NULL,
  `started_at` timestamp NULL DEFAULT NULL,
  `completed_at` timestamp NULL DEFAULT NULL,
  `labour_cost` decimal(10,2) DEFAULT NULL,
  `parts_cost` decimal(10,2) DEFAULT NULL,
  `total_cost` decimal(10,2) DEFAULT NULL,
  `checklist_summary` varchar(1000) DEFAULT NULL,
  `raised_at` timestamp NOT NULL,
  `created_at` timestamp NOT NULL,
  `updated_at` timestamp NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_service_event_tenant_type_number` (`tenant_id`,`event_type`,`event_number`),
  KEY `idx_service_event_tenant_asset` (`tenant_id`,`asset_id`),
  KEY `idx_service_event_tenant_status` (`tenant_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `aiq_vendor` (
  `id` bigint NOT NULL,
  `tenant_id` varchar(50) NOT NULL,
  `vendor_code` varchar(30) NOT NULL,
  `vendor_name` varchar(100) NOT NULL,
  `vendor_type` varchar(20) NOT NULL,
  `gst_number` varchar(20) DEFAULT NULL,
  `contact_email` varchar(100) DEFAULT NULL,
  `contact_phone` varchar(20) DEFAULT NULL,
  `is_active` tinyint NOT NULL DEFAULT '1',
  `created_at` timestamp NOT NULL,
  `updated_at` timestamp NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_vendor_tenant_code` (`tenant_id`,`vendor_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `aiq_visit_asset_capture` (
  `id` bigint NOT NULL,
  `tenant_id` varchar(50) NOT NULL,
  `visit_id` varchar(50) NOT NULL,
  `visit_date` date NOT NULL,
  `outlet_code` varchar(50) NOT NULL,
  `territory_code` varchar(30) DEFAULT NULL,
  `salesman_code` varchar(50) NOT NULL,
  `asset_id` bigint NOT NULL,
  `asset_number` varchar(30) NOT NULL,
  `is_planned_visit` tinyint NOT NULL DEFAULT '0',
  `presence_status` varchar(20) NOT NULL,
  `scan_method` varchar(20) DEFAULT NULL,
  `scan_value` varchar(100) DEFAULT NULL,
  `purity_raw_score` smallint DEFAULT NULL,
  `purity_pct` decimal(5,2) DEFAULT NULL,
  `purity_source` varchar(20) NOT NULL DEFAULT 'MANUAL',
  `purity_ai_confidence` decimal(5,2) DEFAULT NULL,
  `condition_grade` varchar(20) DEFAULT NULL,
  `condition_source` varchar(20) NOT NULL DEFAULT 'MANUAL',
  `condition_ai_confidence` decimal(5,2) DEFAULT NULL,
  `working_status` varchar(20) DEFAULT NULL,
  `working_status_source` varchar(20) NOT NULL DEFAULT 'MANUAL',
  `competitor_present` tinyint NOT NULL DEFAULT '0',
  `competitor_brand` varchar(50) DEFAULT NULL,
  `competitor_pct` decimal(5,2) DEFAULT NULL,
  `branding_status` varchar(20) DEFAULT NULL,
  `photo_url_1` varchar(500) DEFAULT NULL,
  `photo_url_2` varchar(500) DEFAULT NULL,
  `photo_url_3` varchar(500) DEFAULT NULL,
  `gps_lat` decimal(10,8) DEFAULT NULL,
  `gps_lng` decimal(11,8) DEFAULT NULL,
  `gps_accuracy_m` decimal(8,2) DEFAULT NULL,
  `captured_offline` tinyint NOT NULL DEFAULT '0',
  `synced_at` timestamp NULL DEFAULT NULL,
  `captured_at` timestamp NOT NULL,
  `created_at` timestamp NOT NULL,
  `notes` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_visit_capture_tenant_asset` (`tenant_id`,`asset_id`),
  KEY `idx_visit_capture_tenant_visit` (`tenant_id`,`visit_id`),
  KEY `idx_visit_capture_tenant_outlet` (`tenant_id`,`outlet_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

